/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICarbonReset: typeof import('~icons/carbon/reset')['default']
    ICarbonSettings: typeof import('~icons/carbon/settings')['default']
    IHeroiconsUser: typeof import('~icons/heroicons/user')['default']
    IMdiAccountGroup: typeof import('~icons/mdi/account-group')['default']
    IMdiBell: typeof import('~icons/mdi/bell')['default']
    IMdiChartBellCurve: typeof import('~icons/mdi/chart-bell-curve')['default']
    IMdiChartBox: typeof import('~icons/mdi/chart-box')['default']
    IMdiChartLine: typeof import('~icons/mdi/chart-line')['default']
    IMdiCounter: typeof import('~icons/mdi/counter')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiMinusCircle: typeof import('~icons/mdi/minus-circle')['default']
    IMdiPalette: typeof import('~icons/mdi/palette')['default']
    IMdiPlusCircle: typeof import('~icons/mdi/plus-circle')['default']
    IMdiTable: typeof import('~icons/mdi/table')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
